/*
  File: app/constants/theme.ts
  Purpose: Shared theme colours, SVG icons, shared components & data
*/

// ─── RE-EXPORT everything screens need ───────────────────────────────────────

export const C = {
  bg: "#0d0618",
  bgDeep: "#080412",
  card: "rgba(255,255,255,0.055)" as const,
  border: "rgba(255,255,255,0.09)" as const,
  purple: "#6d28d9",
  purpleMid: "#7c3aed",
  purpleLight: "#8b5cf6",
  purpleGlow: "#a78bfa",
  purpleFaint: "rgba(109,40,217,0.18)" as const,
  white: "#ffffff",
  whiteSoft: "rgba(255,255,255,0.88)" as const,
  whiteMuted: "rgba(255,255,255,0.55)" as const,
  faint: "rgba(255,255,255,0.32)" as const,
  online: "#10d9a0",
  navBg: "#0a0415" as const,
};

export const CHATS = [
  {
    id: 1,
    name: "Study Group 300L",
    preview: "Don't forget the assignment deadline tmr",
    time: "09:42",
    unread: 5,
    initials: "SG",
    color: "#6d28d9",
    online: true,
    pinned: true,
  },
  {
    id: 2,
    name: "Amaka Obi",
    preview: "I'll send you the notes right now",
    time: "09:18",
    unread: 2,
    initials: "AO",
    color: "#be185d",
    online: true,
    pinned: false,
  },
  {
    id: 3,
    name: "CSC Department",
    preview: "Lecture moved to LT3 tomorrow",
    time: "Yesterday",
    unread: 12,
    initials: "CS",
    color: "#0e7490",
    online: false,
    pinned: false,
  },
  {
    id: 4,
    name: "Tunde Bello",
    preview: "Did you collect the form already?",
    time: "Yesterday",
    unread: 0,
    initials: "TB",
    color: "#b45309",
    online: false,
    pinned: false,
  },
  {
    id: 5,
    name: "Hostel Block D",
    preview: "Water is back on everyone!",
    time: "Mon",
    unread: 3,
    initials: "HD",
    color: "#065f46",
    online: true,
    pinned: false,
  },
  {
    id: 6,
    name: "Fatima Usman",
    preview: "See you at the library at 4pm",
    time: "Mon",
    unread: 0,
    initials: "FU",
    color: "#5b21b6",
    online: false,
    pinned: false,
  },
  {
    id: 7,
    name: "Assignments 400L",
    preview: "Has anyone done question 3b yet?",
    time: "Sun",
    unread: 7,
    initials: "AS",
    color: "#1e40af",
    online: false,
    pinned: false,
  },
];
